name: Continuous Integration

on: [pull_request]

jobs:
  analyze:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configuring java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Configuring flutter environment
        uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: '2.0.x'
          channel: 'stable'
      - name: "Get dependencies"
        run: flutter packages get
      - name: "Dart Analyze"
        run: flutter analyze

  format:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configuring java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Configuring flutter environment
        uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: '2.0.x'
          channel: 'stable'
      - name: "Get dependencies"
        run: flutter packages get
      - name: "Formatter"
        run: flutter format --set-exit-if-changed .

  build_example:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configuring java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Configuring flutter environment
        uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: '2.0.x'
          channel: 'stable'
      - name: "Get dependencies"
        run: flutter packages get
      - name: "Build example bundle"
        run: cd example && flutter build appbundle

  build_example_web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configuring java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Configuring flutter environment
        uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: '2.0.x'
          channel: 'stable'
      - name: Getting dependencies
        run: flutter packages get
      - name: Build example website
        run: flutter config --enable-web && cd example && flutter build web

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configuring java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Configuring flutter environment
        uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: '2.0.x'
          channel: 'stable'
      - name: "Get dependencies"
        run: flutter packages get
      - name: "Flutter Test"
        run: flutter test .